name: docs_env_xwmt
channels:
  - conda-forge
dependencies:
  - python==3.12
  - black
  - pylint
  - pytest
  - netcdf4
  - nc-time-axis
  - ipython
  - jupyter
  - sphinx
  - nbsphinx
  - jupyter-sphinx
  - sphinx-book-theme
  - matplotlib
  - pip